### ISSUE TITLE
Incompatible with PHP 7 ?

### ISSUE THREAD

**Issue by schplurtz** [fpoirotte/XRL#9]
Hello,
I wanted to test the command line embeded in the phar, but got a PHP fatal error.
I use PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS ) on ubuntu 16.04 and today bzip2 phar version of XRL.

The command line

```
php XRL-2.0.x-dev.phar http://bloink/api/xmlrpc system.getTime
```

And the error I get

```
PHP Fatal error:  Cannot use 'Int' as class name as it is reserved in phar:///tmp/XRL-2.0.x-dev.phar/src/Types/Int.php on line 7
```

**Comment by fpoirotte** [comment]
I just released XRL v3.0.0 which fixes this issue.
You can grab the updated phar from https://github.com/fpoirotte/XRL/releases/tag/3.0.0
